### ISSUE TITLE
Server Access Required for APCE- (3865 Vipin Verma)

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-FileServer-Permissions#3]
Server Access (Read/Write) required for below given folders to Mr. Vipin Verma-3865, Mr, Somiya Guha sent request for the same.

1. APCE\FGD\2 PROPOSALS
2. APCE\FGD\5 CONTRACT ENGINEERING.

@Isgec/dc-infra-team , Myself Praveen Kumar is working for the same.

**Comment by msrawat-isgec** [comment]
Dear Mr. Soumya,

 

Needful is done. Please check with Mr. Vipin.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: helpdesk.noida63-request@isgec.co.in
[mailto:helpdesk.noida63-request@isgec.co.in] On Behalf Of Soumya Guha
Sent: 19 February 2021 11:53
To: Praveen Kumar
Cc: vipin.verma@isgec.co.in; helpdesk.noida63@isgec.co.in; 'amrit kumar
halder'
Subject: RE: Handover of mechanical seal document

 

Adding Halder sir.

 

Thanks & Regards,

Soumya Guha

Dy. Manager,

Process-Lead

Process & Proposal, APCE

Ph: +91-9432954049

Te: +91-120-408-5922

Description: Isgec eSign

A-5, Sector 63, Noida - 201 301 U.P., India

 

J Every 3000 sheets of paper cost us a tree. 

Let's consider our environmental responsibility before printing this e-mail
- Save paper

 

From: Soumya Guha [mailto:soumya.guha@isgec.co.in] 
Sent: Friday, February 19, 2021 11:52 AM
To: Praveen Kumar (praveen1.kumar@isgec.co.in)
Cc: vipin.verma@isgec.co.in; helpdesk.noida63@isgec.co.in
Subject: FW: Handover of mechanical seal document

 

Please arrange for access.

 

Thanks & Regards,

Soumya Guha

Dy. Manager,

Process-Lead

Process & Proposal, APCE

Ph: +91-9432954049

Te: +91-120-408-5922

Description: Isgec eSign

A-5, Sector 63, Noida - 201 301 U.P., India

 

J Every 3000 sheets of paper cost us a tree. 

Let's consider our environmental responsibility before printing this e-mail
- Save paper

 

From: Amrit kumar Halder [mailto:amrithalder@isgec.co.in] 
Sent: Friday, February 19, 2021 11:49 AM
To: 'Soumya Guha'
Subject: RE: Handover of mechanical seal document

 

Approved.

 

Regards,

Amrit

 

From: Soumya Guha [mailto:soumya.guha@isgec.co.in] 
Sent: Friday, February 19, 2021 11:13 AM
To: 'amrit kumar halder'
Subject: FW: Handover of mechanical seal document

 

Re-forwarded.

 

Thanks & Regards,

Soumya Guha

Dy. Manager,

Process-Lead

Process & Proposal, APCE

Ph: +91-9432954049

Te: +91-120-408-5922

Description: Isgec eSign

A-5, Sector 63, Noida - 201 301 U.P., India

 

J Every 3000 sheets of paper cost us a tree. 

Let's consider our environmental responsibility before printing this e-mail
- Save paper

 

From: Soumya Guha [mailto:soumya.guha@isgec.co.in] 
Sent: Thursday, February 18, 2021 4:51 PM
To: 'amrit kumar halder' (amrithalder@isgec.co.in)
Subject: FW: Handover of mechanical seal document

 

Sir,

 

Please approve.

 

Thanks & Regards,

Soumya Guha

Dy. Manager,

Process-Lead

Process & Proposal, APCE

Ph: +91-9432954049

Te: +91-120-408-5922

Description: Isgec eSign

A-5, Sector 63, Noida - 201 301 U.P., India

 

J Every 3000 sheets of paper cost us a tree. 

Let's consider our environmental responsibility before printing this e-mail
- Save paper

 

From: Vipin Verma [mailto:vipin.verma@isgec.co.in] 
Sent: Thursday, February 18, 2021 4:49 PM
To: 'Soumya Guha'
Cc: 'amrit kumar halder'; 'Debapriyo Bhaduri'
Subject: RE: Handover of mechanical seal document

 

Dear Mr. Soumya,

As discussed, below mentioned folder access (R/W) would be required.

 

APCE\FGD\2 PROPOSALS



 

APCE\FGD\5 CONTRACT ENGINEERING



 

 

Regards

Vipin Verma

 

From: Debapriyo Bhaduri [mailto:debapriyo.bhaduri@isgec.co.in] 
Sent: Thursday, February 18, 2021 10:49 AM
To: 'Soumya Guha'; vipin.verma@isgec.co.in
Cc: 'amrit kumar halder'
Subject: RE: Handover of mechanical seal document

 

Ok, I have no issue.

 

 

With Regards,

Debapriyo Bhaduri

Dept: FGD Process & Proposal

Extn : 01204085975
Ph No : 9599213667

 

 

 

From: Soumya Guha [mailto:soumya.guha@isgec.co.in] 
Sent: Thursday, February 18, 2021 10:19 AM
To: 'Debapriyo Bhaduri'; vipin.verma@isgec.co.in
Cc: 'amrit kumar halder'
Subject: RE: Handover of mechanical seal document

 

Sorry. I will not be able to turn up for the meeting in 1st half due to
other urgent customer (TAQA) meeting. can we do it in 2nd half 4:00pm?

 

Thanks & Regards,

Soumya Guha

Dy. Manager,

Process-Lead

Process & Proposal, APCE

Ph: +91-9432954049

Te: +91-120-408-5922

Description: Isgec eSign

A-5, Sector 63, Noida - 201 301 U.P., India

 

J Every 3000 sheets of paper cost us a tree. 

Let's consider our environmental responsibility before printing this e-mail
- Save paper

 

From: Debapriyo Bhaduri [mailto:debapriyo.bhaduri@isgec.co.in] 
Sent: Wednesday, February 17, 2021 12:59 PM
To: 'Soumya Guha'
Cc: 'amrit kumar halder'
Subject: RE: Handover of mechanical seal document

 

We would discuss on the same on tomorrow at 11 AM  for the handover. 

 

PLEASE FIND THE MECHANICAL SEAL FLUSH  PLAN DOCUMENTS IN THE FOLLOWING
LOCATION :

 

A:\FGD\5 CONTRACT ENGINEERING\2.) FS0001-NTPC Kudgi\29 Equipments\10. Slurry
Pumps\9. Mechanical seal plan

 

A:\FGD\5 CONTRACT ENGINEERING\3.) FS0002-NTPC Gadarwara\29 Equipments\10.
Slurry Pumps\Mechanical  SEAL Spec

 

With Regards,

Debapriyo Bhaduri

Dept: FGD Process & Proposal

Extn : 01204085975
Ph No : 9599213667

 

 

 

 

From: Soumya Guha [mailto:soumya.guha@isgec.co.in] 
Sent: Tuesday, February 16, 2021 5:50 PM
To: debapriyo.bhaduri@isgec.co.in
Cc: 'amrit kumar halder'
Subject: Handover of mechanical seal document

 

Please handover mechanical seal post order document as discussed with Boss.

 

Thanks & Regards,

Soumya Guha

Dy. Manager,

Process-Lead

Process & Proposal, APCE

Ph: +91-9432954049

Te: +91-120-408-5922

Description: Isgec eSign

A-5, Sector 63, Noida - 201 301 U.P., India

 

J Every 3000 sheets of paper cost us a tree. 

Let's consider our environmental responsibility before printing this e-mail
- Save paper
